config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  get 'home' => 'static#home', as: :home
  
  resources :channels, only: [:new, :create, :show]
  
  get ':channel_id/clone' => 'channels#clone', as: :clone_channel
  post ':channel_id/clone' => 'channels#clone'

  get ':channel_id/unlock' => 'channels#unlock', as: :unlock_channel
  post ':channel_id/unlock' => 'channels#unlock'
  
  get ':channel_id/new' => 'subscriptions#new', as: :new_channel_subscription
  post ':channel_id/create' => 'subscriptions#create', as: :channel_subscriptions

  patch ':channel_id/:feed_id' => 'subscriptions#update', as: :channel_subscription
  delete ':channel_id/:feed_id' => 'subscriptions#destroy'
    

end

app/models/channel.rb
require 'securerandom'

class Channel < ActiveRecord::Base
  # Relationships
  has_many :subscriptions
  has_many :feeds, through: :subscriptions
  
  # Validation
  validates :name, presence: true
  validates :password, length: {minimum: 5}, allow_nil: true
  
  has_secure_password
  
  # Hooks
  before_validation do
    self.name = SecureRandom.hex 4 if self.name.nil?
  end
  
  def to_param
    self.name
  end
  
  def verify_password password
    if !self.authenticate password
      self.errors.add :password, 'does not match'
      false
    else
      true
    end
  end

  def add_subscriptions subscriptions
    subscriptions.map {|x| x.feed}.each {|x| Subscription.create channel: self, feed: x}
  end
  
  def news count = 90
    news = []
    
    self.subscriptions.map {|x| x.feed}.each do |feed|
      news = news + feed.news
    end
    
    return news.sort_by {|x| x[:published_at]}.last(count).reverse || []
  end

  def to_rss count = 90
    self.subscriptions.map {|x| x.feed.to_rss}
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :require_channel
  skip_before_action :require_channel, only: [:new, :create]

  def new
  end
  
  def create
    channel = Channel.new params.require(:channel).permit(:password, :password_confirmation)

    if !channel.save
      @errors = channel.errors
      render 'new'
    else
      unlock_channel channel
      redirect_to channel_path(channel)
    end
  end

  def show
    respond_to do |format|
      format.rss {render layout: false}
      format.html {}
    end
  end
    
  def clone
    if params.include? :channel
      channel = Channel.new params.require(:channel).permit(:password, :password_confirmation)
      channel.add_subscriptions @channel.subscriptions

      if !channel.save
        @errors = channel.errors
      else
        unlock_channel channel
        redirect_to channel_path(channel)
      end
    end
  end

  def unlock
    if params.include? :channel
      if !@channel.verify_password params.require(:channel).permit(:password)[:password]
        @errors = @channel.errors
      else
        unlock_channel @channel
        redirect_to channel_path(@channel)
      end
    end
  end
end

app/views/channels/clone.html.haml
.container
  = form_for :channel, url: clone_channel_path(@channel) do |f|
    = validation_for 'form-group', :password, params[f.object_name.to_sym], @errors do
      = f.label :password, 'Password', {class: 'form-control-label'}
      = f.password_field :password, class: form_control_for(:password, params[f.object_name.to_sym], @errors), value: value_for(:password, f)
      
    = validation_for 'form-group', :password_confirmation, params[f.object_name.to_sym], @errors do
      = f.label :password_confirmation, 'Password confirmation', {class: 'form-control-label'}
      = f.password_field :password_confirmation, class: form_control_for(:password_confirmation, params[f.object_name.to_sym], @errors), value: value_for(:password_confirmation, f)

    = f.submit 'Clone', class: 'btn btn-primary form-control'

app/views/channels/new.html.haml
.container
  = form_for :channel, url: channels_path do |f|
    = validation_for 'form-group', :password, params[f.object_name.to_sym], @errors do
      = f.label :password, 'Password', {class: 'form-control-label'}
      = f.password_field :password, class: form_control_for(:password, params[f.object_name.to_sym], @errors), value: value_for(:password, f)

    = validation_for 'form-group', :password_confirmation, params[f.object_name.to_sym], @errors do
      = f.label :password_confirmation, 'Password confirmation', {class: 'form-control-label'}
      = f.password_field :password_confirmation, class: form_control_for(:password_confirmation, params[f.object_name.to_sym], @errors), value: value_for(:password_confirmation, f)

    -#= validation_for 'form-group', :captcha, params[f.object_name.to_sym], @errors do
      = recaptcha_tags

    = f.submit 'Create', class: 'btn btn-primary form-control'

app/views/channels/show.html.haml
.container-fluid
  .row
    .col-2
      .mb-1
        %h6
          Subscriptions

          - if channel_unlocked? @channel
            .float-right
              %a{href: new_channel_subscription_path(@channel)}
                %i.icon.ion-plus
        %ul
          - @channel.subscriptions.map {|x| {object: x.feed, atom: x.feed.to_atom}}.each do |feed|
            %li
              %a.abbreviate-text{href: feed[:atom].link, target: '_blank'}
                = feed[:atom].title

              - if channel_unlocked? @channel
                .float-right
                  = link_to channel_subscription_path(@channel, feed[:object]), method: :patch do
                    %i.icon.ion-refresh.hidden-icon
                  = link_to channel_subscription_path(@channel, feed[:object]), method: :delete do
                    %i.icon.ion-trash-b.hidden-icon

      %h6
        Channel

        - if channel_locked? @channel
          .float-right
            %a{href: unlock_channel_path(@channel)}
              %i.icon.ion-locked

      %ul
        %li
          = link_to 'Clone', clone_channel_path(@channel), method: :post
        -#%li
          = 'Settings'

    .col-10
      .row
        .col-12
          %h5
            Updates
            
            .float-right.text-right
              = link_to channel_path(@channel, format: :rss) do
                %i.icon.ion-social-rss
          
          .tilemap
            -#Channel.first.feeds.map {|x| x.youtube_videos.to_a}.flatten
            
            - @channel.feeds.map {|x| x.youtube_videos.to_a.map {|x| x.to_atom}}.flatten.each_slice(6) do |slice|
              .card-deck.ml-0.mr-0
                - slice.each do |update|
                  .card.tile
                    %img.card-img-top.img-responsive{src: update.optional[:thumbnail], alt: 'thumbnail'}
                      
                    .card-body
                      %p.card-text.abbreviate-text
                        %a{href: update.link, target: '_blank'}
                          = update.title

                    -#.card-footer
                      .float-left.text-left
                        %small
                          %a{target: '_blank', href: update[:link]}
                            = 'test'

                      .float-right.text-right
                        %small.text-muted.abbreviate-text
                          = "#{time_ago_in_words(update[:published_at])} ago"
                          
                - (6 - slice.size).times do
                  .card.tile.invisible

app/views/channels/show.rss.haml
!!! XML
%rss{version: '2.0'}
  %channel
    %title= "synfeed"
    %link= request.original_url

    - @channel.news.each do |update|
      %item
        %title= update[:title]
        %link= update[:link]
        %author= update[:author][:title]
        %guid= update[:id]
        %pubDate= update[:published_at]

app/views/channels/unlock.html.haml
.container
  = form_for :channel, url: unlock_channel_path(@channel) do |f|
    = validation_for 'form-group', :password, params[f.object_name.to_sym], @errors do
      = f.label :password, 'Password', {class: 'form-control-label'}
      = f.password_field :password, class: form_control_for(:password, params[f.object_name.to_sym], @errors), value: value_for(:password, f)
      
    = f.submit 'Clone', class: 'btn btn-primary form-control'